### ISSUE TITLE
Several errors...

### ISSUE THREAD

**Issue by Naustdal** [gody01/ecovent_v2#12]
**Update for binary_sensor.vento_expert_fan_filter_replacement_status fails**
`Logger: homeassistant.helpers.entity
Source: custom_components/ecovent_v2/sensor.py:266
Integration: Vento Eco Vent v 2.0
First occurred: 16:47:37 (6 occurrences)
Last logged: 17:01:58

Update for binary_sensor.vento_expert_fan_filter_replacement_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 428, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 189, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 215, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/ecovent_v2/sensor.py", line 235, in native_value
    self._attr_native_value = self._method()
  File "/config/custom_components/ecovent_v2/sensor.py", line 266, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
AttributeError: 'int' object has no attribute 'split'
`
**Error adding entities for domain sensor with platform ecovent_v2
Error while setting up ecovent_v2 platform for sensor**

`Logger: homeassistant.components.sensor
Source: custom_components/ecovent_v2/sensor.py:266
Integration: sensor (documentation, issues)
First occurred: 16:47:06 (4 occurrences)
Last logged: 17:01:27

Error adding entities for domain sensor with platform ecovent_v2
Error while setting up ecovent_v2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/ecovent_v2/sensor.py", line 235, in native_value
    self._attr_native_value = self._method()
  File "/config/custom_components/ecovent_v2/sensor.py", line 266, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
AttributeError: 'int' object has no attribute 'split'
`
**[139646456843136] 'int' object has no attribute 'split'**

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ecovent_v2/sensor.py:266
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:06:38 (1 occurrences)
Last logged: 17:06:38

[139646456843136] 'int' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/ecovent_v2/fan.py", line 155, in async_turn_on
    await self.coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 215, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/ecovent_v2/sensor.py", line 235, in native_value
    self._attr_native_value = self._method()
  File "/config/custom_components/ecovent_v2/sensor.py", line 266, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
AttributeError: 'int' object has no attribute 'split'

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5

I sussessfull added the device. Show 1 device and 25 entier. 
![Skjermbilde 2023-03-28 170949](https://user-images.githubusercontent.com/93888061/228283536-a5c8900a-f8bf-4bf9-810c-d37b19db7f19.png)
 Its respind on network ping, and unit is online and respond on Blauberg Vento mobile application. 
Its not working true Home Assistant.

**Comment by gody01** [comment]
Thank You for report.

Can You please let me know:
- which verison of ecovent_v2 You have ?
- which version of firmware is on device

An if You can download https://github.com/gody01/pyEcoventV2 and in test.py change IP address of 10.94.0.106 to IP of Your fan.

Than run with python3 test.py and look at output of line with battery_voltage: 3258 mV

It looks, like Your fan does not report battery voltage with unit (mV) at the end. Perhaps they changed something in newer firmware version.

**Comment by Naustdal** [comment]
Hi and thank you for qick respond,

Version of ecovent_2" is: 0.9.2
Blauberg Vento Expert A50-1 S W - Found version 1.1.2, when connected with USB to fan.

I downloaded and added pyEcoventV2 to Home Assistant. Changed the ip adress in test.py and restarted.
I dosent know to to run python3 test.pyI, but should it not start automatic after restart ?

Got some new errors...

 **Update for binary_sensor.vento_expert_fan_filter_replacement_status fails**
`Denne feilen stammer fra en tilpasset integrasjon.

Logger: homeassistant.helpers.entity
Source: custom_components/ecovent_v2/sensor.py:266
Integration: Vento Eco Vent v 2.0
First occurred: 15:22:07 (2 occurrences)
Last logged: 15:22:37

Update for binary_sensor.vento_expert_fan_filter_replacement_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 428, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 189, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 215, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/ecovent_v2/sensor.py", line 235, in native_value
    self._attr_native_value = self._method()
  File "/config/custom_components/ecovent_v2/sensor.py", line 266, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
AttributeError: 'int' object has no attribute 'split'

**Error handling request**

`Logger: aiohttp.server
Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:403
First occurred: 15:21:49 (1 occurrences)
Last logged: 15:21:49

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
`
**Error adding entities for domain sensor with platform ecovent_v2**
**Error while setting up ecovent_v2 platform for sensor**

`Logger: homeassistant.components.sensor
Source: custom_components/ecovent_v2/sensor.py:266
Integration: sensor (documentation, issues)
First occurred: 15:21:36 (2 occurrences)
Last logged: 15:21:36

Error adding entities for domain sensor with platform ecovent_v2
Error while setting up ecovent_v2 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/ecovent_v2/sensor.py", line 235, in native_value
    self._attr_native_value = self._method()
  File "/config/custom_components/ecovent_v2/sensor.py", line 266, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
AttributeError: 'int' object has no attribute 'split'
`

**Comment by Naustdal** [comment]
Got additional some error when try to start/stop...

**Unexpected error fetching ecovent_v2 data: 0**
`Denne feilen stammer fra en tilpasset integrasjon.

Logger: custom_components.ecovent_v2
Source: custom_components/ecovent_v2/__init__.py:89
Integration: Vento Eco Vent v 2.0
First occurred: 15:58:26 (2 occurrences)
Last logged: 15:59:16

Unexpected error fetching ecovent_v2 data: 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ecovent_v2/__init__.py", line 89, in _async_update_data
    self._fan.update()
  File "/usr/local/lib/python3.10/site-packages/ecoventv2/__init__.py", line 370, in update
    return self.do_func(self.func['read'], request)
  File "/usr/local/lib/python3.10/site-packages/ecoventv2/__init__.py", line 359, in do_func
    self.parse_response(response)
  File "/usr/local/lib/python3.10/site-packages/ecoventv2/__init__.py", line 477, in parse_response
    setattr ( self, self.params[int(response[:2].hex(),16)][0], response[2:].hex())
KeyError: 0
`

Attached some screenshot from phone:;
![Screenshot_20230329_160059](https://user-images.githubusercontent.com/93888061/228563861-eb10e001-4121-4e01-a41c-dae3e5b78bbb.jpg)
![Screenshot_20230329_160115](https://user-images.githubusercontent.com/93888061/228563897-5c756422-5559-4048-8d07-35781329318d.jpg)

The fan has been setting up with use of USB and then connected to my local Wifi. Its have fixed ip adress and i can ping ti. Show fine and can controll it whit Blauberg app on phone.

**Comment by gody01** [comment]
test.py is not started by home assistant. This is comand line tool, which queries fans and prints results on screen.

In the first post, error is still the same:
voltage = int(self._fan.battery_voltage.split()[0])
AttributeError: 'int' object has no attribute 'split'

This means, that result from fan is not in format 2350 mV as in my fans, but only number.

In second post, it could be, thatn pyEcovent in custom_components breaks sometging. Better to remove.

test.py can be invoked on any computer with python installed not necessary on HomeAssistant.



On phone App, can You select Firmware option and post what it print on the screen.

A have:
Firmware version: 0.4
Firmware date: 20/12/2019

**Comment by Naustdal** [comment]
Ok :)

On phone app, im only getting app version as 2.1.6, nothing about firmware.. But as mention, i got version 1.1.2, when connected with USB to fan and used software.

From manual, i cant find anything about battery, not eather inclued in SmartHome manual.
VENTO Expert A50-1 W usermanual: https://blaubergventilatoren.de/en/download/6739
SmartHome manual: https://blaubergventilatoren.de/en/download/6815

**Comment by gody01** [comment]
Oh. Those manuals are not for V2 versions.

Perhaps You should try this one:
https://github.com/aglehmann/home_assistant_ecovent

**Comment by gody01** [comment]
Or maybe this one could work for You:

https://www.dingus.dk/dukaone-ventilation-with-heat-exchanger-and-home-assistant/

**Comment by Naustdal** [comment]
Thank you.
dukaone; I dosent understand how to impliment the fan.. This code isent my strongest side..

**Comment by sfrevel** [comment]
Just have a look at my comment [here](https://github.com/gody01/ecovent_v2/issues/20#issuecomment-2222337535) - this *split* error looks really the same to me - so double check you pin/password of the device you want to initialize!

I have added the Raumluft Oxxify Smart 50 which is pretty much the same fan device - it has just an other device id. And the fans work with this integration. But I installed the HA custom component manually and als the ecoventV2 library. So there are some small changes to the code in my environment to load the library from the custom component directory off HA.
