### ISSUE TITLE
Since 2023.5 not working

### ISSUE THREAD

**Issue by thecem** [gody01/ecovent_v2#14]
Hi since the update tp 2023.5.x the integration is not working and throws this error:
If you need more infomration I could provide what you need.

Vent FW: 0.7 

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/ecovent_v2/__init__.py:49
Integration: EcoVentV2
First occurred: 12:19:31 (1 occurrences)
Last logged: 12:19:31

Error setting up entry FAN WZ DG 004A00314D43570F for ecovent_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ecovent_v2/__init__.py", line 49, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by gody01** [comment]
Which version of integration do You use ?

This problem, reported in https://github.com/gody01/ecovent_v2/issues/9, was fixed in 0.9.1 (release is now 0.9.2).

**Comment by thecem** [comment]
I‘m was on 0.9.2. After you asked I reinstalled an rebooted, now it works.

**Comment by AndyNew2** [comment]
ready to close as well. All good now.
