### ISSUE TITLE
Integration crash when Humidity senser is altered in Blauberg app

### ISSUE THREAD

**Issue by Styx85** [gody01/ecovent_v2#17]
Hi there,
I get an reproducable crash of the integration in HA when I change the hunidity sensor in thie original blauberg app (enable/disable or threshold change) triggering the boost status. Error log as below:

`2023-08-05 21:25:31.424 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities fan.vento_expert_fan are missing or not currently available
2023-08-05 21:25:31.429 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities fan.vento_expert_fan are missing or not currently available
2023-08-05 21:25:31.432 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities fan.vento_expert_fan are missing or not currently available
2023-08-05 21:25:52.586 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Vento Expert Fan 0039003B54435712 for ecovent_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/__init__.py", line 37, in async_setup_entry
    coordinator = VentoFanDataUpdateCoordinator(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/__init__.py", line 74, in __init__
    self._fan.init_device()
  File "/usr/local/lib/python3.11/site-packages/ecoventv2/__init__.py", line 225, in init_device
    return self.update()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ecoventv2/__init__.py", line 370, in update
    return self.do_func(self.func['read'], request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ecoventv2/__init__.py", line 359, in do_func
    self.parse_response(response)
  File "/usr/local/lib/python3.11/site-packages/ecoventv2/__init__.py", line 477, in parse_response
    setattr ( self, self.params[int(response[:2].hex(),16)][0], response[2:].hex())
  File "/usr/local/lib/python3.11/site-packages/ecoventv2/__init__.py", line 548, in boost_status
    self._boost_status = self.statuses[val]
                         ~~~~~~~~~~~~~^^^^^
KeyError: 2`

**Comment by gody01** [comment]
Thank You for report.

**Comment by Styx85** [comment]
And sorry I forgot to mention my model. See screenshot.
![Screenshot_2023-08-09-08-33-04-492_io homeassistant companion android](https://github.com/gody01/ecovent_v2/assets/32103696/15c4ff55-1690-40f7-b21a-a2230a13968f)

**Comment by gody01** [comment]
Should be fixed in 0.9.4
This was undocumented behaviour of Vento Fans, where boost_status can have aditional value of 2 (delayed, after sensor condition is no longer active).

**Comment by Styx85** [comment]
Thanks, so far I confirm it as solved. I will test it in several edge cases
on the weekend.

When I have a look at the Blauberg Homepage (english one) a generation 3 is
launched, therefore there seem to be some additions to the protocol or
usage of previously masked functions. But so far I did not have a firmware
update.

Am Mi., 9. Aug. 2023 um 16:24 Uhr schrieb Matjaž Godec <
***@***.***>:

**Comment by Styx85** [comment]
I confirm this issue fixed. No further crashes during long term tests, running stable now for nearly 3 months.

**Comment by AndyNew2** [comment]
Propose to close this issue.
@gody01

**Comment by Komzpa** [comment]
Hi @Styx85, this was already reported as fixed earlier, and release `1.2.6` keeps that path covered.

The merged work in #44 preserves profile-specific status enums and tolerant parsing for values like boost/status `2`, so changing humidity/boost-related state in the vendor app should not crash the integration with `KeyError: 2`.

Could you please confirm whether this is still stable on `1.2.6`? If yes, I think this issue can be closed.
