### ISSUE TITLE
keine Bedienung möglich

### ISSUE THREAD

**Issue by westi2000** [gody01/ecovent_v2#20]
Hallo, ich bekomme diese Meldung : 

Fehler beim Aufrufen des Diensts fan/turn_off. 'int' object has no attribute 'split'

leider kann ich den Blauberg Vento Expert A50-1 S10 W V.2 nicht schalten mit HA, per App ist alles OK. Hat jemand diesen Fehler beheben können?

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:732
First occurred: 17:56:54 (33 occurrences)
Last logged: 18:13:38

Update for binary_sensor.vento_expert_fan_filter_replacement_status fails
Update for binary_sensor.bad_fan_filter_replacement_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 507, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 240, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 475, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 235, in native_value
    self._attr_native_value = self._method()
                              ^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 266, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'

**Comment by DuncanIdaho89** [comment]
Hi, I've got the same issue here.

I'm pretty new to this party, so I don't really know how to check into this myself. If someone could look into this, that would be great!

Log:

Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:945
Erstmals aufgetreten: 16:59:23 (2 Vorkommnisse)
Zuletzt protokolliert: 16:59:53

Update for binary_sensor.vento_expert_fan_filter_replacement_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 535, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 112, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 294, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 497, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 548, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 190, in native_value
    self._attr_native_value = self._method()
                              ^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 221, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'

**Comment by DuncanIdaho89** [comment]
YES!! Ohmygod thank you very much, that was exacly the issue. I changed the password in the official app and in my secrets.yaml.
Had to delete and re-add the vent in the integration, but looks like it's working now!

**Comment by Cornflakew** [comment]
Hello, 
I´m also having the issue mentioned above. I can ping the device and it is shown with several entities. but there is no activation possible. I receive the same faliure: 'int' object has no attribute 'split'
I have still not figured out where to find the "ecoventv2 library" to make the chages mentiond from @sfrevel . 
Maybe I am to dumb to install this python library additionaly. I have only installed ecovent_v.2 via hacs. 
Are there any suggestions?

**Comment by sfrevel** [comment]
I did not install via hacs, I just copy the library code in a folder like this /homeassistant/custom_components/ecovent_v2/ and changed the __init__.py file locally

**Comment by DuncanIdaho89** [comment]
Hi,
as @sfrevel already mentioned, it is just cosmetics. You can find it in "custom_components/ecovent_v2/" using the file editor.

But you don't need to. Try to change the password in your Blauberg app and also in your secrets.yaml. If it still doesn't work, delete and readd the vent in the integration.

Worked for me and I didn't change any files.

**Comment by Cornflakew** [comment]
Thank you all for your suggestions. 

I tried ti fix it this way and changed PW via the app and then in new Device when starting the integration newly. as I do not use secrets.yaml this seemed to be the best way. 
My ID was entered with the line ID_001E.... or ID: 001E... both ended in a positive result for the device search. 
nevertheless I still receive the error "'int' object has no attribute 'split'" when trying to turn the device on. 

I have installed the integration directly via hacs with the url "https://github.com/gody01/ecovent_v2".
I still dont know if afterwards I missed to install the library from the url "https://github.com/gody01/pyEcoventV2" ??? If so to do... how? 
The device I am using is VENTO Expert A50-1 S10 W V.2 (NOT the DUO!)

Maybe you have another idea. The integration is for me not hobby. I have two of those which should work combined in our basement for the childrensrooms in relation of the absolute humidity inside and outside via HA. thats why I chose these fans with WLAN. 
I appreciate your support very much! 

LOG:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecovent_v2
Quelle: helpers/debounce.py:137
Integration: Vento Eco Vent v 2.0
Erstmals aufgetreten: 09:46:50 (21 Vorkommnisse)
Zuletzt protokolliert: 09:59:43

Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.ecovent_v2.VentoFanDataUpdateCoordinator object at 0x7f426a1cddf0>>
Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.ecovent_v2.VentoFanDataUpdateCoordinator object at 0x7f424f7b70b0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 190, in native_value
    self._attr_native_value = self._method()
                              ^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 221, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'

**Comment by sfrevel** [comment]
Pretty sure your PW is not set correctly, just double check.

**Comment by Cornflakew** [comment]
I tried hard and made several changes without any success. 
The PW is absolutely correct and simple. that worke in the blauberg app. 
I deinstalled ecovent_v2 twice, lat time I had the idea that there may be lags in my System to interprete python, so i installed the integration pyscript first. 
An Installation without HACS was not succesfull either to me so I gave up and installed it again from hacs... 
same result. 
interesting is, that the device is recognized with fals ID numbers... but if this is any reason? I dont know. 
is there any other integration fpr python that has to be installed first?

**Comment by gody01** [comment]
ID format on Blauberg vents is like this: 003A00345842570A
Only numbers.
Vent has to be in master mode, to talk with integration.
Default password is 1111.

**Comment by Cornflakew** [comment]
tried again:
fan is in master mode. 
ID was not again acceptet without the letters ID in front. so I changed the fan in Wifi-connection mode by holding the button of the  fan 5 sec (all leds blinking).  

PW ohny accepted with my newly changed one. 

then I got 25 entities, but no more device... by trying to change the fan status to on the same failure was sent...  :(
after a few minutes (leds no more blinking) the entities are still there, but not reachable... 
 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecovent_v2
Quelle: helpers/debounce.py:137
Integration: Vento Eco Vent v 2.0
Erstmals aufgetreten: 14:47:53 (5 Vorkommnisse)
Zuletzt protokolliert: 14:49:53

Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.ecovent_v2.VentoFanDataUpdateCoordinator object at 0x7f29a0a3ea50>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 190, in native_value
    self._attr_native_value = self._method()
                              ^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/sensor.py", line 221, in battery_voltage
    voltage = int(self._fan.battery_voltage.split()[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'

**Comment by Komzpa** [comment]
Hi @westi2000, @DuncanIdaho89, @Cornflakew and @sfrevel, release `1.2.6` should improve this failure mode.

The logs here showed `AttributeError: 'int' object has no attribute 'split'` in the battery voltage sensor. The merged work in #44 hardens battery voltage parsing so it accepts numeric values as well as strings like `"3300 mV"` and returns `None` for invalid/missing values instead of crashing entity updates.

Please test `1.2.6`. If control still fails after this, the remaining problem may be configuration/password/device-id related rather than this sensor crash, so fresh logs from `1.2.6` would be useful.
