### ISSUE TITLE
Firmware 0.8 (04/11/2023) Unknown error 

### ISSUE THREAD

**Issue by rubatec** [gody01/ecovent_v2#23]
It´s not possible to add fan device with correct password and Device ID -> unknown error
So I entered a wrong password -> fan device could be added but of course no values available.

Then I change the password in Vento App to the "wrong" password, so that the passwords of the fan and in the integration are the same. But this leads to "error during setup" of the integration

Debug protocol:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/__init__.py", line 38, in async_setup_entry
    coordinator = VentoFanDataUpdateCoordinator(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecovent_v2/__init__.py", line 75, in __init__
    self._fan.init_device()
  File "/usr/local/lib/python3.12/site-packages/ecoventv2/__init__.py", line 231, in init_device
    return self.update()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ecoventv2/__init__.py", line 376, in update
    return self.do_func(self.func['read'], request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ecoventv2/__init__.py", line 365, in do_func
    self.parse_response(response)
  File "/usr/local/lib/python3.12/site-packages/ecoventv2/__init__.py", line 483, in parse_response
    setattr ( self, self.params[int(response[:2].hex(),16)][0], response[2:].hex())
  File "/usr/local/lib/python3.12/site-packages/ecoventv2/__init__.py", line 680, in filter_timer_countdown
    val = int(input,16).to_bytes(3,'big')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: int too big to convert

Has anyone had this problem before?

**Comment by rubatec** [comment]
HACS V2.0.0
Vento Eco Vent v 2.0 V1.0.1
Firmware 0.8

**Comment by stichtingdspprt** [comment]
I have the same issue. I also found the problem and after some deep digging I was able to solve it. 
It appears that the filter timer now returns 4 bytes instead of 3 bytes (unclear what the fourth byte is for, it has a 00-value). If the code in __init__.py in the pyEcoventv2 module on line 680 is changed from:

val = int(input,16).to_bytes(3,'big') 
into 
val = int(input,16).to_bytes(4,'big')

the fourth byte is now included (but ignored) and the filter timer now picks the right bytes to calculate the remaining filter time. 
The fix should be done in https://github.com/gody01/pyEcoventV2/blob/master/ecoventv2/__init__.py

Since I do not know if this fix is backwards compatible, I leave it to the author of this repo to include it or not. 
The code is not very robust when it comes to the parsing of the response from the fans. I was able to defer this from a similar API description to be found on : https://blaubergventilatoren.de/download/9398. This describes the structure of the packets, but is not up to date with this firmware version. If anyone has some more up to date info, please add that to the comments.

**Comment by rvanderwouw** [comment]
I have the same issue. I also found the problem and after some deep digging I was able to solve it.
It appears that the filter timer now returns 4 bytes instead of 3 bytes (unclear what the fourth byte is for, it has a 00-value). If the code in init.py in the pyEcoventv2 module on line 680 is changed from:

val = int(input,16).to_bytes(3,'big')
into
val = int(input,16).to_bytes(4,'big')

the fourth byte is now included (but ignored) and the filter timer now picks the right bytes to calculate the remaining filter time.
The fix should be done in https://github.com/gody01/pyEcoventV2/blob/master/ecoventv2/__init__.py

Since I do not know if this fix is backwards compatible, I leave it to the author of this repo to include it or not.
The code is not very robust when it comes to the parsing of the response from the fans. I was able to defer this from a similar API description to be found on : https://blaubergventilatoren.de/download/9398. This describes the structure of the packets, but is not up to date with this firmware version. If anyone has some more up to date info, please add that to the comments.

I still have to figure out how to make the change work in homeassistant, since the problem is not in the integration itself but in the pyEcoventV2 module that is used by the integration.

**Comment by rvanderwouw** [comment]
I have forked this repo and the pyEconVentV2 library for this specific firmware (0.8). Not sure if it is backwards compatible, so I have not sent in a pull request. Feel free to use my fork. [https://github.com/rvanderwouw/ecovent_v2](url)

**Comment by rubatec** [comment]
Just testet it with FW 0.9 (before already with FW 0.8) and was able to add the fans.

Thank you so much. I will close this issue
