### ISSUE TITLE
Error setting up entry for ecovent_v2

### ISSUE THREAD

**Issue by thecem** [gody01/ecovent_v2#5]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/ecovent_v2/__init__.py:76
Integration: EcoVentV2
First occurred: 13:11:24 (1 occurrences)
Last logged: 13:11:24

Error setting up entry FAN  for ecovent_v2
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 306, in send
    payload = self.get_header() + data
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 280, in get_header
    id_size = self.get_size(self._id)
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 277, in get_size
    return hex(len(str)).replace("0x","").zfill(2)
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ecovent_v2/__init__.py", line 39, in async_setup_entry
    coordinator = VentoFanDataUpdateCoordinator(
  File "/config/custom_components/ecovent_v2/__init__.py", line 76, in __init__
    self._fan.init_device()
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 223, in init_device
    self.update()
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 354, in update
    self.do_func(self.func['read'], request)
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 344, in do_func
    self.send(data)
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 310, in send
    except self.socket.timeout as err:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by Komzpa** [comment]
Hi @thecem, could you please retest this with release `1.2.6`?

This issue is from an older setup path, but #44 significantly hardened the vendored protocol client and setup/update flow: packet building/parsing, socket exception handling, and initialization are now handled inside the integration with executor-backed calls.

If this old setup error is no longer reproducible on `1.2.6`, I think the issue can be closed. If it still happens, please add a fresh traceback from `1.2.6`.
