### ISSUE TITLE
Home Assistant won't start when fan is offline

### ISSUE THREAD

**Issue by rbovenkampclearict** [gody01/ecovent_v2#6]
Today I put a fan offline because I was painting the wall the fan was mounted on and what I saw after a few minutes was that home assistant was completely offline and won't start until I put the fan back online. How can I change this behaviour?

**Comment by gody01** [comment]
Thank You for report.
I'll look into this. It seems like endles timeout repeat is not OK.

**Comment by gody01** [comment]
Should be sorted in latest version.

**Comment by gody01** [comment]
Logs should be in homeassistant core logs.

Setings/System/Logs.

**Comment by rbovenkampclearict** [comment]
It seems that the old config is still active somehow.

This error originated from a custom integration.

Logger: custom_components.ecovent_v2.config_flow
Source: config_entries.py:1309 
Integration: EcoVentV2 
First occurred: August 28, 2022, 23:20:23 (7 occurrences) 
Last logged: 13:41:48

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/ecovent_v2/config_flow.py", line 130, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1309, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow("already_configured")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by gody01** [comment]
Is this resolved in latest versions ?
